displayName: Car Sales Marktposition Researcher
schemaName: copilots_header_vwitabe_agent1SSdXmv
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    default-2.1.0:
      content:
        capabilities:
          $kind: GptCapabilities
          diagnostics:
          webBrowsing: true

        conversationStarters:
        description:
        displayName: Agent
        instructions:

      spec:
        connectors:

    GenerativeActionsEnabled: true

  isAgentConnectable: false
  gPTSettings:
    defaultSchemaName: copilots_header_vwitabe_agent1SSdXmv.gpt.default

  aISettings:
    useModelKnowledge: false
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: false
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-03-31T08:53:20.0000000Z
template: default-2.1.0
language: 1031