displayName: Car Sales Marktposition Agent
schemaName: copilots_header_vwitabe_agent2
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: false
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: copilots_header_vwitabe_agent2.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: false
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: false
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-04-16T05:32:21.0000000Z
template: default-2.1.0
language: 1031